######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 9 10:38:48 2011
######################################################################

QT += network
CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imdb.h mini_gui.h
SOURCES += imdb.cpp main.cpp mini_gui.cpp
