######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 24 15:23:26 2011
######################################################################

QT       += core gui network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imdb.h mainwindow.h
FORMS += historique.ui mainwindow.ui
SOURCES += imdb.cpp main.cpp mainwindow.cpp
